version: '3.8'

services:
  
  python_project:
    image: lakky1/hakata_python_project
    container_name: python_project
    tty: true
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATA_PATH=${DATA_PATH}
      - SITE_DATA_PATH=${SITE_DATA_PATH}
      - INDEX_PATH=${INDEX_PATH}
      - REDIS_PATH=redis:6379

  # frontend_project:
  #   build:
  #     context: ./frontend_type_project
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"