version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
      
  python-backend:
    image:  maincompose.azurecr.io/semi_webapp_backend:latest
    container_name: python-project
    tty: true
    ports:
      - 4000:4000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATA_PATH=${DATA_PATH}
      - INDEX_PATH=${INDEX_PATH}
      - IS_DOCKER=true

  frontend-project:
    image: maincompose.azurecr.io/frontend_project:latest
    ports:
      - "3000:3000"