version: '3.8'

services:
  
  python_project:
    image: lakky1/hakata_python_project
    container_name: python_project
    tty: true
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATA_PATH=${DATA_PATH}
      - SITE_DATA_PATH=${SITE_DATA_PATH}
      - INDEX_PATH=${INDEX_PATH}
      - REDIS_PATH=redis:6379
<<<<<<< HEAD

  # frontend_project:
  #   build:
  #     context: ./frontend_type_project
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"
=======
    ports:
      - "4000:4000" 

  frontend_project:
    build:
      context: ./next_app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
>>>>>>> 1c9609db9c8ce1ad8c235e3ec4b0882e3e66b18a
